version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgresClient
    restart: always
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: clientManagement
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: